export const {
  VITE_CHAIN_API_URL: CHAIN_API_URL,
  VITE_CHAIN_ID: CHAIN_ID,
  VITE_WALLET_URL: WALLET_URL,
  VITE_OIG_ACCOUNT: OIG_ACCOUNT,
  VITE_DECIDE_ACCOUNT: DECIDE_ACCOUNT
} = import.meta.env;
