export const {
  VITE_CHAIN_API_URL: CHAIN_API_URL,
  VITE_CHAIN_ID: CHAIN_ID,
  VITE_WALLET_URL: WALLET_URL,
  VITE_OIG_ACCOUNT: OIG_ACCOUNT,
  VITE_DECIDE_ACCOUNT: DECIDE_ACCOUNT,
  VITE_OIG_CALENDAR_EMBED: OIG_CALENDAR_EMBED,
  VITE_MEDIUM_API_KEY: MEDIUM_API_KEY,
  VITE_NOTION_API_KEY: NOTION_API_KEY
} = import.meta.env;
